### ISSUE TITLE
Next.js is missing as dependency

### ISSUE THREAD

**Issue by bonndan** [issaafalkattan/react-landing-page-template-2021#1]
This morning I tried to run `yarn` with the result "command next is not defined".

    npm install yarn

did the trick. You might want to add it as dependency.

**Comment by issaafalkattan** [comment]
Yarn is not necessary for running the project; the same can be achieved with `npm install` + `npm run dev`, so perhaps it shouldn't be part of the dependencies. What do you think, @bonndan?

**Comment by bonndan** [comment]
My point is that `next` appears to be missing as dependency.

**Comment by bonndan** [comment]
I have cloned the repo into a new directory and the error was gone. Most likey it was my fault. You can close the issue.
