### ISSUE TITLE
Site returns a 404 by default

### ISSUE THREAD

**Issue by samuel-henry** [issaafalkattan/react-landing-page-template-2021#5]
Thank you for creating and sharing this!

**Describe the bug**
Site returns a 404 by default

**To Reproduce**
1.  git clone https://github.com/issaafalkattan/react-landing-page-template-2021.git
2. cd react-landing-page-template-2021
3. yarn
4. yarn dev
5. Visit http://localhost:3000/

**Expected behavior**
Returns a 200

**Screenshots**
![Screen Shot 2022-01-19 at 5 53 36 PM](https://user-images.githubusercontent.com/2597585/150248439-08748448-77ed-4e5d-bfd1-c0fa53cd9af6.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSX
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] Version 97.0.4692.71 (Official Build) (x86_64)

**Additional context**
This is happening both locally and when I deploy my site to AWS Amplify

Thank you for creating this template!

**Comment by issaafalkattan** [comment]
This should be fixed now! Thanks for reporting!

**Comment by samuel-henry** [comment]
Thank you! This fix works for me
